// Anchor Thread Library - Auto-generated
// DO NOT EDIT - Generated from TypeScript sources

use super::{ThreadColor, ThreadBrand};

pub fn get_anchor_threads() -> Vec<ThreadColor> {
    vec![
        ThreadColor {
            code: "1".to_string(),
            name: "White".to_string(),
            rgb: [255, 255, 255],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "2".to_string(),
            name: "Tin White".to_string(),
            rgb: [252, 251, 248],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "275".to_string(),
            name: "Off White".to_string(),
            rgb: [248, 246, 240],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "926".to_string(),
            name: "Ecru".to_string(),
            rgb: [240, 234, 218],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "830".to_string(),
            name: "Cream".to_string(),
            rgb: [253, 249, 227],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "885".to_string(),
            name: "Cream Light".to_string(),
            rgb: [255, 251, 233],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "886".to_string(),
            name: "Cream Very Light".to_string(),
            rgb: [255, 253, 241],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "403".to_string(),
            name: "Black".to_string(),
            rgb: [0, 0, 0],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "400".to_string(),
            name: "Steel Gray Dark".to_string(),
            rgb: [52, 52, 52],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "401".to_string(),
            name: "Steel Gray Medium".to_string(),
            rgb: [105, 105, 105],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "398".to_string(),
            name: "Pearl Gray Dark".to_string(),
            rgb: [130, 130, 130],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "399".to_string(),
            name: "Pearl Gray Medium".to_string(),
            rgb: [155, 155, 155],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "397".to_string(),
            name: "Pearl Gray Light".to_string(),
            rgb: [180, 180, 180],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "234".to_string(),
            name: "Pearl Gray Very Light".to_string(),
            rgb: [210, 210, 210],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "235".to_string(),
            name: "Pearl Gray Ultra Light".to_string(),
            rgb: [230, 230, 230],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "13".to_string(),
            name: "Coral Red Light".to_string(),
            rgb: [255, 140, 140],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "11".to_string(),
            name: "Coral Red".to_string(),
            rgb: [255, 120, 120],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "10".to_string(),
            name: "Coral Red Medium".to_string(),
            rgb: [255, 95, 95],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "9".to_string(),
            name: "Coral Red Dark".to_string(),
            rgb: [255, 70, 70],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "46".to_string(),
            name: "Christmas Red".to_string(),
            rgb: [205, 0, 0],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "47".to_string(),
            name: "Christmas Red Bright".to_string(),
            rgb: [227, 0, 0],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "19".to_string(),
            name: "Christmas Red Dark".to_string(),
            rgb: [178, 0, 0],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "20".to_string(),
            name: "Christmas Red Very Dark".to_string(),
            rgb: [143, 0, 0],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "22".to_string(),
            name: "Burgundy".to_string(),
            rgb: [115, 0, 0],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "44".to_string(),
            name: "Carmine".to_string(),
            rgb: [200, 45, 45],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "35".to_string(),
            name: "Terra Cotta Light".to_string(),
            rgb: [224, 112, 95],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "5975".to_string(),
            name: "Terra Cotta".to_string(),
            rgb: [190, 85, 70],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "339".to_string(),
            name: "Terra Cotta Dark".to_string(),
            rgb: [165, 60, 45],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "341".to_string(),
            name: "Terra Cotta Very Dark".to_string(),
            rgb: [135, 40, 30],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "23".to_string(),
            name: "Rose Pink Light".to_string(),
            rgb: [255, 200, 200],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "24".to_string(),
            name: "Rose Pink".to_string(),
            rgb: [255, 175, 175],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "25".to_string(),
            name: "Rose Pink Medium".to_string(),
            rgb: [245, 145, 155],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "27".to_string(),
            name: "Rose Pink Dark".to_string(),
            rgb: [225, 100, 120],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "28".to_string(),
            name: "Rose Pink Very Dark".to_string(),
            rgb: [200, 65, 90],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "29".to_string(),
            name: "Raspberry Light".to_string(),
            rgb: [220, 90, 120],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "31".to_string(),
            name: "Raspberry".to_string(),
            rgb: [200, 60, 100],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "33".to_string(),
            name: "Raspberry Dark".to_string(),
            rgb: [175, 35, 75],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "36".to_string(),
            name: "Dusty Rose Light".to_string(),
            rgb: [225, 175, 180],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "38".to_string(),
            name: "Dusty Rose".to_string(),
            rgb: [200, 145, 155],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "39".to_string(),
            name: "Dusty Rose Medium".to_string(),
            rgb: [180, 120, 135],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "40".to_string(),
            name: "Dusty Rose Dark".to_string(),
            rgb: [155, 90, 105],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "42".to_string(),
            name: "Dusty Rose Very Dark".to_string(),
            rgb: [130, 65, 80],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "48".to_string(),
            name: "Baby Pink".to_string(),
            rgb: [255, 215, 220],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "49".to_string(),
            name: "Baby Pink Medium".to_string(),
            rgb: [255, 190, 200],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "50".to_string(),
            name: "Baby Pink Dark".to_string(),
            rgb: [250, 165, 180],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "52".to_string(),
            name: "Wild Rose Light".to_string(),
            rgb: [240, 185, 190],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "54".to_string(),
            name: "Wild Rose".to_string(),
            rgb: [225, 155, 165],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "55".to_string(),
            name: "Wild Rose Medium".to_string(),
            rgb: [205, 125, 140],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "57".to_string(),
            name: "Wild Rose Dark".to_string(),
            rgb: [180, 95, 110],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "59".to_string(),
            name: "Wild Rose Very Dark".to_string(),
            rgb: [155, 65, 80],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "316".to_string(),
            name: "Burnt Orange Light".to_string(),
            rgb: [255, 175, 100],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "314".to_string(),
            name: "Burnt Orange".to_string(),
            rgb: [245, 145, 65],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "329".to_string(),
            name: "Burnt Orange Medium".to_string(),
            rgb: [225, 120, 45],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "330".to_string(),
            name: "Burnt Orange Dark".to_string(),
            rgb: [200, 95, 25],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "332".to_string(),
            name: "Burnt Orange Very Dark".to_string(),
            rgb: [170, 70, 15],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "303".to_string(),
            name: "Pumpkin Light".to_string(),
            rgb: [255, 165, 75],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "304".to_string(),
            name: "Pumpkin".to_string(),
            rgb: [250, 140, 45],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "323".to_string(),
            name: "Pumpkin Medium".to_string(),
            rgb: [235, 115, 25],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "324".to_string(),
            name: "Pumpkin Dark".to_string(),
            rgb: [210, 90, 10],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "326".to_string(),
            name: "Pumpkin Very Dark".to_string(),
            rgb: [180, 70, 5],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "1001".to_string(),
            name: "Melon Light".to_string(),
            rgb: [255, 190, 150],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "8".to_string(),
            name: "Melon".to_string(),
            rgb: [255, 165, 120],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "1002".to_string(),
            name: "Peach".to_string(),
            rgb: [255, 185, 140],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "4146".to_string(),
            name: "Apricot Light".to_string(),
            rgb: [255, 200, 165],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "313".to_string(),
            name: "Apricot".to_string(),
            rgb: [255, 175, 130],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "293".to_string(),
            name: "Canary Light".to_string(),
            rgb: [255, 255, 170],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "289".to_string(),
            name: "Canary".to_string(),
            rgb: [255, 255, 130],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "290".to_string(),
            name: "Canary Medium".to_string(),
            rgb: [255, 250, 90],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "291".to_string(),
            name: "Canary Dark".to_string(),
            rgb: [255, 240, 50],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "295".to_string(),
            name: "Lemon Light".to_string(),
            rgb: [255, 255, 180],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "288".to_string(),
            name: "Lemon".to_string(),
            rgb: [255, 255, 140],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "286".to_string(),
            name: "Lemon Medium".to_string(),
            rgb: [255, 250, 100],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "298".to_string(),
            name: "Lemon Dark".to_string(),
            rgb: [255, 235, 60],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "300".to_string(),
            name: "Topaz Light".to_string(),
            rgb: [255, 230, 160],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "301".to_string(),
            name: "Topaz".to_string(),
            rgb: [255, 220, 120],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "302".to_string(),
            name: "Topaz Medium".to_string(),
            rgb: [255, 205, 80],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "305".to_string(),
            name: "Topaz Dark".to_string(),
            rgb: [245, 185, 50],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "306".to_string(),
            name: "Topaz Very Dark".to_string(),
            rgb: [230, 165, 30],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "307".to_string(),
            name: "Golden Yellow Light".to_string(),
            rgb: [255, 215, 100],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "308".to_string(),
            name: "Golden Yellow".to_string(),
            rgb: [255, 200, 60],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "309".to_string(),
            name: "Golden Yellow Medium".to_string(),
            rgb: [245, 180, 35],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "310".to_string(),
            name: "Golden Yellow Dark".to_string(),
            rgb: [230, 160, 20],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "238".to_string(),
            name: "Christmas Green Light".to_string(),
            rgb: [150, 210, 150],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "239".to_string(),
            name: "Christmas Green".to_string(),
            rgb: [110, 185, 110],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "226".to_string(),
            name: "Christmas Green Medium".to_string(),
            rgb: [75, 160, 75],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "227".to_string(),
            name: "Christmas Green Dark".to_string(),
            rgb: [45, 135, 45],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "228".to_string(),
            name: "Christmas Green Very Dark".to_string(),
            rgb: [20, 110, 20],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "203".to_string(),
            name: "Parrot Green Light".to_string(),
            rgb: [130, 200, 100],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "204".to_string(),
            name: "Parrot Green".to_string(),
            rgb: [95, 175, 65],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "205".to_string(),
            name: "Parrot Green Medium".to_string(),
            rgb: [60, 150, 35],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "206".to_string(),
            name: "Parrot Green Dark".to_string(),
            rgb: [35, 125, 15],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "208".to_string(),
            name: "Parrot Green Very Dark".to_string(),
            rgb: [15, 100, 5],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "240".to_string(),
            name: "Spring Green Light".to_string(),
            rgb: [180, 225, 155],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "241".to_string(),
            name: "Spring Green".to_string(),
            rgb: [145, 205, 120],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "242".to_string(),
            name: "Spring Green Medium".to_string(),
            rgb: [110, 180, 85],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "243".to_string(),
            name: "Spring Green Dark".to_string(),
            rgb: [75, 155, 55],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "244".to_string(),
            name: "Spring Green Very Dark".to_string(),
            rgb: [45, 130, 30],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "253".to_string(),
            name: "Fern Green Light".to_string(),
            rgb: [145, 175, 125],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "254".to_string(),
            name: "Fern Green".to_string(),
            rgb: [115, 150, 95],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "255".to_string(),
            name: "Fern Green Medium".to_string(),
            rgb: [85, 125, 65],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "256".to_string(),
            name: "Fern Green Dark".to_string(),
            rgb: [55, 100, 40],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "257".to_string(),
            name: "Fern Green Very Dark".to_string(),
            rgb: [35, 80, 25],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "259".to_string(),
            name: "Avocado Light".to_string(),
            rgb: [165, 175, 130],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "260".to_string(),
            name: "Avocado".to_string(),
            rgb: [140, 155, 105],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "261".to_string(),
            name: "Avocado Medium".to_string(),
            rgb: [115, 135, 80],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "262".to_string(),
            name: "Avocado Dark".to_string(),
            rgb: [90, 110, 55],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "263".to_string(),
            name: "Avocado Very Dark".to_string(),
            rgb: [65, 85, 35],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "264".to_string(),
            name: "Moss Green Light".to_string(),
            rgb: [185, 195, 130],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "265".to_string(),
            name: "Moss Green".to_string(),
            rgb: [160, 175, 105],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "266".to_string(),
            name: "Moss Green Medium".to_string(),
            rgb: [135, 155, 80],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "267".to_string(),
            name: "Moss Green Dark".to_string(),
            rgb: [110, 130, 55],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "268".to_string(),
            name: "Moss Green Very Dark".to_string(),
            rgb: [85, 105, 35],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "269".to_string(),
            name: "Olive Light".to_string(),
            rgb: [150, 145, 95],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "280".to_string(),
            name: "Olive".to_string(),
            rgb: [130, 125, 75],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "281".to_string(),
            name: "Olive Medium".to_string(),
            rgb: [110, 105, 55],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "268".to_string(),
            name: "Olive Dark".to_string(),
            rgb: [90, 85, 40],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "128".to_string(),
            name: "Delft Blue Light".to_string(),
            rgb: [200, 215, 235],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "129".to_string(),
            name: "Delft Blue".to_string(),
            rgb: [175, 195, 225],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "130".to_string(),
            name: "Delft Blue Medium".to_string(),
            rgb: [145, 170, 210],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "131".to_string(),
            name: "Delft Blue Dark".to_string(),
            rgb: [115, 145, 190],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "132".to_string(),
            name: "Delft Blue Very Dark".to_string(),
            rgb: [85, 120, 170],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "117".to_string(),
            name: "Wedgwood Light".to_string(),
            rgb: [175, 195, 215],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "118".to_string(),
            name: "Wedgwood".to_string(),
            rgb: [145, 170, 195],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "119".to_string(),
            name: "Wedgwood Medium".to_string(),
            rgb: [115, 145, 175],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "120".to_string(),
            name: "Wedgwood Dark".to_string(),
            rgb: [85, 120, 150],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "121".to_string(),
            name: "Wedgwood Very Dark".to_string(),
            rgb: [60, 95, 125],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "140".to_string(),
            name: "Royal Blue Light".to_string(),
            rgb: [130, 160, 210],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "141".to_string(),
            name: "Royal Blue".to_string(),
            rgb: [100, 130, 190],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "142".to_string(),
            name: "Royal Blue Medium".to_string(),
            rgb: [70, 100, 170],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "143".to_string(),
            name: "Royal Blue Dark".to_string(),
            rgb: [45, 75, 145],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "144".to_string(),
            name: "Royal Blue Very Dark".to_string(),
            rgb: [25, 50, 120],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "145".to_string(),
            name: "Sky Blue Light".to_string(),
            rgb: [185, 220, 245],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "146".to_string(),
            name: "Sky Blue".to_string(),
            rgb: [155, 200, 235],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "147".to_string(),
            name: "Sky Blue Medium".to_string(),
            rgb: [125, 175, 220],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "148".to_string(),
            name: "Sky Blue Dark".to_string(),
            rgb: [95, 150, 200],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "149".to_string(),
            name: "Sky Blue Very Dark".to_string(),
            rgb: [65, 125, 180],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "150".to_string(),
            name: "Cornflower Light".to_string(),
            rgb: [170, 190, 225],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "152".to_string(),
            name: "Cornflower".to_string(),
            rgb: [135, 160, 205],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "153".to_string(),
            name: "Cornflower Medium".to_string(),
            rgb: [100, 130, 185],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "154".to_string(),
            name: "Cornflower Dark".to_string(),
            rgb: [70, 100, 165],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "155".to_string(),
            name: "Peacock Blue Light".to_string(),
            rgb: [125, 180, 200],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "156".to_string(),
            name: "Peacock Blue".to_string(),
            rgb: [90, 155, 180],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "158".to_string(),
            name: "Peacock Blue Medium".to_string(),
            rgb: [55, 130, 160],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "159".to_string(),
            name: "Peacock Blue Dark".to_string(),
            rgb: [30, 105, 140],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "160".to_string(),
            name: "Peacock Blue Very Dark".to_string(),
            rgb: [10, 80, 115],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "167".to_string(),
            name: "Navy Blue Light".to_string(),
            rgb: [100, 115, 145],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "168".to_string(),
            name: "Navy Blue".to_string(),
            rgb: [70, 85, 120],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "169".to_string(),
            name: "Navy Blue Medium".to_string(),
            rgb: [45, 60, 95],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "170".to_string(),
            name: "Navy Blue Dark".to_string(),
            rgb: [25, 40, 70],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "176".to_string(),
            name: "Turquoise Light".to_string(),
            rgb: [145, 215, 215],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "177".to_string(),
            name: "Turquoise".to_string(),
            rgb: [110, 195, 200],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "178".to_string(),
            name: "Turquoise Medium".to_string(),
            rgb: [75, 175, 185],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "179".to_string(),
            name: "Turquoise Dark".to_string(),
            rgb: [45, 150, 165],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "85".to_string(),
            name: "Lavender Light".to_string(),
            rgb: [220, 200, 225],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "86".to_string(),
            name: "Lavender".to_string(),
            rgb: [200, 175, 210],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "87".to_string(),
            name: "Lavender Medium".to_string(),
            rgb: [175, 150, 190],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "88".to_string(),
            name: "Lavender Dark".to_string(),
            rgb: [150, 125, 170],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "89".to_string(),
            name: "Lavender Very Dark".to_string(),
            rgb: [125, 100, 150],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "95".to_string(),
            name: "Violet Light".to_string(),
            rgb: [195, 175, 210],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "96".to_string(),
            name: "Violet".to_string(),
            rgb: [170, 145, 195],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "97".to_string(),
            name: "Violet Medium".to_string(),
            rgb: [145, 115, 175],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "98".to_string(),
            name: "Violet Dark".to_string(),
            rgb: [120, 85, 155],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "99".to_string(),
            name: "Violet Very Dark".to_string(),
            rgb: [95, 55, 135],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "100".to_string(),
            name: "Purple Light".to_string(),
            rgb: [180, 145, 195],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "101".to_string(),
            name: "Purple".to_string(),
            rgb: [155, 110, 175],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "102".to_string(),
            name: "Purple Medium".to_string(),
            rgb: [130, 75, 155],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "103".to_string(),
            name: "Purple Dark".to_string(),
            rgb: [105, 45, 135],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "104".to_string(),
            name: "Purple Very Dark".to_string(),
            rgb: [80, 20, 110],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "108".to_string(),
            name: "Grape Light".to_string(),
            rgb: [165, 130, 165],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "109".to_string(),
            name: "Grape".to_string(),
            rgb: [140, 100, 145],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "110".to_string(),
            name: "Grape Medium".to_string(),
            rgb: [115, 70, 120],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "111".to_string(),
            name: "Grape Dark".to_string(),
            rgb: [90, 45, 95],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "112".to_string(),
            name: "Grape Very Dark".to_string(),
            rgb: [65, 25, 70],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "358".to_string(),
            name: "Tan Light".to_string(),
            rgb: [225, 195, 160],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "359".to_string(),
            name: "Tan".to_string(),
            rgb: [205, 170, 130],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "360".to_string(),
            name: "Tan Medium".to_string(),
            rgb: [185, 145, 100],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "361".to_string(),
            name: "Tan Dark".to_string(),
            rgb: [160, 120, 75],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "362".to_string(),
            name: "Tan Very Dark".to_string(),
            rgb: [135, 95, 55],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "363".to_string(),
            name: "Golden Brown Light".to_string(),
            rgb: [215, 175, 115],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "365".to_string(),
            name: "Golden Brown".to_string(),
            rgb: [190, 145, 85],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "367".to_string(),
            name: "Golden Brown Medium".to_string(),
            rgb: [165, 115, 55],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "368".to_string(),
            name: "Golden Brown Dark".to_string(),
            rgb: [140, 90, 35],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "369".to_string(),
            name: "Golden Brown Very Dark".to_string(),
            rgb: [115, 70, 20],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "370".to_string(),
            name: "Pecan Light".to_string(),
            rgb: [200, 160, 120],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "371".to_string(),
            name: "Pecan".to_string(),
            rgb: [175, 135, 95],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "372".to_string(),
            name: "Pecan Medium".to_string(),
            rgb: [150, 110, 70],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "373".to_string(),
            name: "Pecan Dark".to_string(),
            rgb: [125, 85, 50],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "374".to_string(),
            name: "Pecan Very Dark".to_string(),
            rgb: [100, 65, 35],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "375".to_string(),
            name: "Mocha Light".to_string(),
            rgb: [185, 145, 115],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "376".to_string(),
            name: "Mocha".to_string(),
            rgb: [160, 120, 90],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "379".to_string(),
            name: "Mocha Medium".to_string(),
            rgb: [135, 95, 65],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "380".to_string(),
            name: "Mocha Dark".to_string(),
            rgb: [110, 70, 45],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "381".to_string(),
            name: "Mocha Very Dark".to_string(),
            rgb: [85, 50, 30],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "382".to_string(),
            name: "Coffee Light".to_string(),
            rgb: [170, 130, 100],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "387".to_string(),
            name: "Coffee".to_string(),
            rgb: [145, 105, 75],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "388".to_string(),
            name: "Coffee Medium".to_string(),
            rgb: [120, 80, 50],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "389".to_string(),
            name: "Coffee Dark".to_string(),
            rgb: [95, 55, 30],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "390".to_string(),
            name: "Coffee Very Dark".to_string(),
            rgb: [70, 35, 15],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "391".to_string(),
            name: "Beige Light".to_string(),
            rgb: [230, 215, 195],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "392".to_string(),
            name: "Beige".to_string(),
            rgb: [210, 190, 165],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "393".to_string(),
            name: "Beige Medium".to_string(),
            rgb: [190, 165, 140],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "394".to_string(),
            name: "Beige Dark".to_string(),
            rgb: [170, 140, 115],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "395".to_string(),
            name: "Beige Very Dark".to_string(),
            rgb: [145, 115, 90],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "896".to_string(),
            name: "Sandalwood Light".to_string(),
            rgb: [220, 200, 175],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "897".to_string(),
            name: "Sandalwood".to_string(),
            rgb: [195, 170, 145],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "898".to_string(),
            name: "Sandalwood Medium".to_string(),
            rgb: [170, 140, 115],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "899".to_string(),
            name: "Sandalwood Dark".to_string(),
            rgb: [145, 115, 90],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "900".to_string(),
            name: "Sandalwood Very Dark".to_string(),
            rgb: [120, 90, 65],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "901".to_string(),
            name: "Mahogany Light".to_string(),
            rgb: [175, 115, 80],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "902".to_string(),
            name: "Mahogany".to_string(),
            rgb: [150, 90, 55],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "903".to_string(),
            name: "Mahogany Medium".to_string(),
            rgb: [125, 65, 35],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "904".to_string(),
            name: "Mahogany Dark".to_string(),
            rgb: [100, 45, 20],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "905".to_string(),
            name: "Mahogany Very Dark".to_string(),
            rgb: [75, 30, 10],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "914".to_string(),
            name: "Chocolate Light".to_string(),
            rgb: [160, 110, 85],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "929".to_string(),
            name: "Chocolate".to_string(),
            rgb: [135, 85, 60],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "936".to_string(),
            name: "Chocolate Medium".to_string(),
            rgb: [110, 60, 40],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "938".to_string(),
            name: "Chocolate Dark".to_string(),
            rgb: [85, 40, 25],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "381".to_string(),
            name: "Chocolate Very Dark".to_string(),
            rgb: [60, 25, 15],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "278".to_string(),
            name: "Metallic Gold Light".to_string(),
            rgb: [255, 220, 130],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "303".to_string(),
            name: "Metallic Gold".to_string(),
            rgb: [245, 195, 75],
            brand: ThreadBrand::Anchor,
            category: None,
        },
        ThreadColor {
            code: "306".to_string(),
            name: "Metallic Gold Dark".to_string(),
            rgb: [220, 165, 35],
            brand: ThreadBrand::Anchor,
            category: None,
        },
    ]
}
