// Kreinik Thread Library - Auto-generated
// DO NOT EDIT - Generated from TypeScript sources

use super::{ThreadColor, ThreadBrand};

pub fn get_kreinik_threads() -> Vec<ThreadColor> {
    vec![
        ThreadColor {
            code: "002".to_string(),
            name: "Gold".to_string(),
            rgb: [255, 215, 0],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "002C".to_string(),
            name: "Gold Cord".to_string(),
            rgb: [255, 215, 0],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "002F".to_string(),
            name: "Gold Fine".to_string(),
            rgb: [255, 215, 0],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "002HL".to_string(),
            name: "Gold Hi Lustre".to_string(),
            rgb: [255, 220, 50],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "002J".to_string(),
            name: "Japan Gold".to_string(),
            rgb: [255, 210, 80],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "002L".to_string(),
            name: "Gold Light".to_string(),
            rgb: [255, 230, 100],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "002P".to_string(),
            name: "Gold Pearl".to_string(),
            rgb: [255, 225, 130],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "002V".to_string(),
            name: "Vintage Gold".to_string(),
            rgb: [200, 160, 60],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "003HL".to_string(),
            name: "Red Gold Hi Lustre".to_string(),
            rgb: [255, 180, 50],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "021".to_string(),
            name: "Copper".to_string(),
            rgb: [184, 115, 51],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "021C".to_string(),
            name: "Copper Cord".to_string(),
            rgb: [184, 115, 51],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "021F".to_string(),
            name: "Copper Filament".to_string(),
            rgb: [184, 115, 51],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "021HL".to_string(),
            name: "Copper Hi Lustre".to_string(),
            rgb: [205, 135, 75],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "202HL".to_string(),
            name: "Aztec Gold".to_string(),
            rgb: [218, 165, 32],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "205C".to_string(),
            name: "Antique Gold".to_string(),
            rgb: [180, 145, 75],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "205HL".to_string(),
            name: "Antique Gold Hi Lustre".to_string(),
            rgb: [195, 160, 85],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "221".to_string(),
            name: "Antique Gold Dark".to_string(),
            rgb: [155, 120, 50],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "3212".to_string(),
            name: "Citron".to_string(),
            rgb: [210, 200, 70],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "001".to_string(),
            name: "Silver".to_string(),
            rgb: [192, 192, 192],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "001C".to_string(),
            name: "Silver Cord".to_string(),
            rgb: [192, 192, 192],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "001F".to_string(),
            name: "Silver Fine".to_string(),
            rgb: [192, 192, 192],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "001HL".to_string(),
            name: "Silver Hi Lustre".to_string(),
            rgb: [210, 210, 215],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "001J".to_string(),
            name: "Japan Silver".to_string(),
            rgb: [195, 195, 200],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "001L".to_string(),
            name: "Silver Light".to_string(),
            rgb: [220, 220, 225],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "001P".to_string(),
            name: "Silver Pearl".to_string(),
            rgb: [230, 230, 235],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "001V".to_string(),
            name: "Vintage Silver".to_string(),
            rgb: [160, 160, 165],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "011HL".to_string(),
            name: "Nickel Hi Lustre".to_string(),
            rgb: [175, 175, 180],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "012".to_string(),
            name: "Pewter".to_string(),
            rgb: [130, 130, 135],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "012HL".to_string(),
            name: "Pewter Hi Lustre".to_string(),
            rgb: [145, 145, 150],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "032".to_string(),
            name: "Pearl".to_string(),
            rgb: [255, 255, 255],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "032C".to_string(),
            name: "Pearl Cord".to_string(),
            rgb: [255, 255, 255],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "032F".to_string(),
            name: "Pearl Fine".to_string(),
            rgb: [255, 255, 255],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "032HL".to_string(),
            name: "Pearl Hi Lustre".to_string(),
            rgb: [255, 255, 255],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "100".to_string(),
            name: "White".to_string(),
            rgb: [255, 255, 255],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "100HL".to_string(),
            name: "White Hi Lustre".to_string(),
            rgb: [255, 255, 255],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "005".to_string(),
            name: "Black".to_string(),
            rgb: [0, 0, 0],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "005C".to_string(),
            name: "Black Cord".to_string(),
            rgb: [0, 0, 0],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "005F".to_string(),
            name: "Black Fine".to_string(),
            rgb: [0, 0, 0],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "005HL".to_string(),
            name: "Black Hi Lustre".to_string(),
            rgb: [25, 25, 25],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "003".to_string(),
            name: "Red".to_string(),
            rgb: [255, 0, 0],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "003F".to_string(),
            name: "Red Fine".to_string(),
            rgb: [255, 0, 0],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "003L".to_string(),
            name: "Red Light".to_string(),
            rgb: [255, 80, 80],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "003HL".to_string(),
            name: "Red Hi Lustre".to_string(),
            rgb: [255, 40, 40],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "031".to_string(),
            name: "Flame".to_string(),
            rgb: [255, 100, 30],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "031HL".to_string(),
            name: "Flame Hi Lustre".to_string(),
            rgb: [255, 115, 45],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "034".to_string(),
            name: "Fuschia".to_string(),
            rgb: [255, 0, 128],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "034HL".to_string(),
            name: "Fuschia Hi Lustre".to_string(),
            rgb: [255, 30, 140],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "042".to_string(),
            name: "Confetti Red".to_string(),
            rgb: [220, 50, 50],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "203HL".to_string(),
            name: "Flame Red".to_string(),
            rgb: [255, 60, 20],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "332".to_string(),
            name: "Christmas Red".to_string(),
            rgb: [200, 0, 0],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "332F".to_string(),
            name: "Christmas Red Fine".to_string(),
            rgb: [200, 0, 0],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "333".to_string(),
            name: "Ruby".to_string(),
            rgb: [155, 25, 50],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "334".to_string(),
            name: "Cranberry".to_string(),
            rgb: [130, 30, 50],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "007".to_string(),
            name: "Pink".to_string(),
            rgb: [255, 192, 203],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "007HL".to_string(),
            name: "Pink Hi Lustre".to_string(),
            rgb: [255, 200, 210],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "024".to_string(),
            name: "Fuchsia".to_string(),
            rgb: [255, 50, 150],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "024HL".to_string(),
            name: "Fuchsia Hi Lustre".to_string(),
            rgb: [255, 70, 160],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "194".to_string(),
            name: "Pale Pink".to_string(),
            rgb: [255, 220, 225],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "9194".to_string(),
            name: "Star Pink".to_string(),
            rgb: [255, 180, 200],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "006".to_string(),
            name: "Orange".to_string(),
            rgb: [255, 165, 0],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "006HL".to_string(),
            name: "Orange Hi Lustre".to_string(),
            rgb: [255, 175, 30],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "052".to_string(),
            name: "Grapefruit".to_string(),
            rgb: [255, 130, 100],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "321".to_string(),
            name: "Tangerine".to_string(),
            rgb: [255, 145, 50],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "326".to_string(),
            name: "Burnt Orange".to_string(),
            rgb: [205, 95, 20],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "091".to_string(),
            name: "Star Yellow".to_string(),
            rgb: [255, 255, 100],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "091HL".to_string(),
            name: "Star Yellow Hi Lustre".to_string(),
            rgb: [255, 255, 120],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "311".to_string(),
            name: "Sunlight".to_string(),
            rgb: [255, 250, 150],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "312".to_string(),
            name: "Sunflower".to_string(),
            rgb: [255, 240, 80],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "2122".to_string(),
            name: "Yellow Gold".to_string(),
            rgb: [255, 220, 50],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "008".to_string(),
            name: "Green".to_string(),
            rgb: [0, 128, 0],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "008HL".to_string(),
            name: "Green Hi Lustre".to_string(),
            rgb: [30, 145, 30],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "009".to_string(),
            name: "Emerald".to_string(),
            rgb: [0, 155, 80],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "009HL".to_string(),
            name: "Emerald Hi Lustre".to_string(),
            rgb: [30, 170, 95],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "015".to_string(),
            name: "Chartreuse".to_string(),
            rgb: [180, 220, 50],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "015HL".to_string(),
            name: "Chartreuse Hi Lustre".to_string(),
            rgb: [195, 230, 70],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "051".to_string(),
            name: "Peacock".to_string(),
            rgb: [50, 130, 130],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "051HL".to_string(),
            name: "Peacock Hi Lustre".to_string(),
            rgb: [70, 145, 145],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "053".to_string(),
            name: "Willow".to_string(),
            rgb: [150, 190, 100],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "322".to_string(),
            name: "Grass Green".to_string(),
            rgb: [80, 160, 60],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "334V".to_string(),
            name: "Vintage Emerald".to_string(),
            rgb: [40, 120, 70],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "3215".to_string(),
            name: "Leaf Green".to_string(),
            rgb: [100, 150, 70],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "3216".to_string(),
            name: "Pine".to_string(),
            rgb: [45, 95, 55],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "5982".to_string(),
            name: "Forest".to_string(),
            rgb: [30, 80, 45],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "006B".to_string(),
            name: "Blue".to_string(),
            rgb: [0, 100, 200],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "014".to_string(),
            name: "Sky Blue".to_string(),
            rgb: [135, 206, 235],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "014HL".to_string(),
            name: "Sky Blue Hi Lustre".to_string(),
            rgb: [150, 215, 240],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "022".to_string(),
            name: "Royal Blue".to_string(),
            rgb: [65, 105, 225],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "022HL".to_string(),
            name: "Royal Blue Hi Lustre".to_string(),
            rgb: [80, 120, 235],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "033".to_string(),
            name: "Confetti Blue".to_string(),
            rgb: [100, 150, 220],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "051B".to_string(),
            name: "Sapphire".to_string(),
            rgb: [30, 70, 160],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "051BHL".to_string(),
            name: "Sapphire Hi Lustre".to_string(),
            rgb: [50, 90, 175],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "052B".to_string(),
            name: "Colonial Blue".to_string(),
            rgb: [80, 120, 180],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "085".to_string(),
            name: "Peacock Blue".to_string(),
            rgb: [0, 100, 140],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "086".to_string(),
            name: "Midnight".to_string(),
            rgb: [25, 40, 95],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "095".to_string(),
            name: "Starburst".to_string(),
            rgb: [100, 165, 215],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "3514".to_string(),
            name: "Blue Ice".to_string(),
            rgb: [180, 210, 240],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "3515".to_string(),
            name: "Wedgewood".to_string(),
            rgb: [100, 140, 190],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "3545".to_string(),
            name: "Navy".to_string(),
            rgb: [20, 35, 80],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "012P".to_string(),
            name: "Purple".to_string(),
            rgb: [128, 0, 128],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "012PHL".to_string(),
            name: "Purple Hi Lustre".to_string(),
            rgb: [145, 30, 145],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "016".to_string(),
            name: "Amethyst".to_string(),
            rgb: [155, 90, 180],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "016HL".to_string(),
            name: "Amethyst Hi Lustre".to_string(),
            rgb: [170, 105, 195],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "023".to_string(),
            name: "Lilac".to_string(),
            rgb: [200, 160, 210],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "023HL".to_string(),
            name: "Lilac Hi Lustre".to_string(),
            rgb: [210, 175, 220],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "026".to_string(),
            name: "Violet".to_string(),
            rgb: [130, 80, 160],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "026HL".to_string(),
            name: "Violet Hi Lustre".to_string(),
            rgb: [145, 95, 175],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "026L".to_string(),
            name: "Violet Light".to_string(),
            rgb: [175, 130, 195],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "3225".to_string(),
            name: "Orchid".to_string(),
            rgb: [185, 110, 175],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "3226".to_string(),
            name: "Grape".to_string(),
            rgb: [100, 50, 100],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "024B".to_string(),
            name: "Brown".to_string(),
            rgb: [139, 90, 43],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "024BHL".to_string(),
            name: "Brown Hi Lustre".to_string(),
            rgb: [155, 105, 60],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "052V".to_string(),
            name: "Vintage Bronze".to_string(),
            rgb: [135, 95, 55],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "022B".to_string(),
            name: "Chestnut".to_string(),
            rgb: [150, 85, 50],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "222".to_string(),
            name: "Bronze".to_string(),
            rgb: [165, 120, 70],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "222HL".to_string(),
            name: "Bronze Hi Lustre".to_string(),
            rgb: [180, 135, 85],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "223".to_string(),
            name: "Antique Bronze".to_string(),
            rgb: [140, 100, 60],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "231".to_string(),
            name: "Autumn Brown".to_string(),
            rgb: [125, 80, 45],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "232".to_string(),
            name: "Chocolate".to_string(),
            rgb: [90, 50, 30],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "5125".to_string(),
            name: "Caramel".to_string(),
            rgb: [175, 130, 80],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "5215".to_string(),
            name: "Toffee".to_string(),
            rgb: [155, 110, 65],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "052G".to_string(),
            name: "Glow White".to_string(),
            rgb: [250, 255, 250],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "054F".to_string(),
            name: "Glow Green".to_string(),
            rgb: [180, 255, 180],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "056F".to_string(),
            name: "Glow Orange".to_string(),
            rgb: [255, 200, 150],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "048".to_string(),
            name: "Confetti Rainbow".to_string(),
            rgb: [255, 128, 128],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
        ThreadColor {
            code: "091V".to_string(),
            name: "Vintage Variegated".to_string(),
            rgb: [200, 175, 130],
            brand: ThreadBrand::Kreinik,
            category: None,
        },
    ]
}
